### ISSUE TITLE
Configure vite to watch assets

### ISSUE THREAD

**Issue by petermakeswebsites** [drannex42/svelte-capacitor#23]
Vite watches the source files but does not watch assets. Would be nice to save a global css file and have it refresh automatically like Svelte does with rollup (at least the way it's configured standard). I tried to do this myself but this is my first time using Vite and I'm not really sure how it works.

Great little template by the way! Thanks for sharing.

**Comment by macleod-ee** [comment]
We decided against watching assets iirc because it caused too many changes (and rebuilds) due to ____some_____ reason in the watcher. I have it commented somewhere in an older version, I'll see about digging it up (if it exists). That's why we had it watch source files and move assets into the assets directory on builds.
