### ISSUE TITLE
Include example of how to integrate with routify

### ISSUE THREAD

**Issue by viblo** [drannex42/svelte-capacitor#6]
This is a very cool project template, very easy to get running. Thanks for putting it together and sharing it!

For those of us that struggle a bit with how to configure and setup things it would be great if you could include an example of how to integrate routify into the template. When I tried the most straight forward way from the routify docs I ended up with a "Error: UMD and IIFE output formats are not supported for code-splitting builds." error.

**Comment by macleod-ee** [comment]
I've been thinking about putting together a full blown framework for this, with components, routing, and the like out of the box. That would likely be a better à candidate for your suggestion

The reason I left out any sort of routing libs is because I wanted this to be as bare bones of a template as possible. I'll close this for now, and if I get around to the framework l'll keep you in the loop.

**Comment by macleod-ee** [comment]
@viblo I have finally found the time to release the v2 of this template, this has routify built in to the template as the default (but easily changed!).

**Comment by viblo** [comment]
@drannex42 Thanks! Only had the chance to try briefly so far, but seems to work well. 
Let me also add that I think you have made a good job with the Readme, very helpful 🥇
